name: remote ssh command
on:
  push:
    branches:
      - main
      - release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to release server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.180.137.15
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/mev.2025fc.xyz/mev-bot-frontend
            git pull --rebase origin main
            npm install
            git checkout -f .
            npm run build


      # - name: deploy to client server
      #   if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: 82.180.137.15
      #     username: root
      #     password: ${{ secrets.PASSWORD }}
      #     port: 22
      #     script: |
      #       cd /www/wwwroot/mev.2025fc.xyz/mev-bot-frontend-remote &&
      #       git pull --rebase origin main &&
      #       npm install &&
      #       git checkout -f . &&
      #       npm run build &&
      #       npm run copy-to-remote

