name: Auto Deploy to Release Server

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 7771207574
          token: 7577717836:AAErCs0jMCGJaaOODpgamZOTzdVyRzCnyUE
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: Deploy to release server
        if: github.ref == 'refs/heads/main'  # 仅 main 分支触发
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.180.137.15
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/account.2025fc.xyz/account-frontend && \
            git pull --rebase origin main && \
            npm install && \
            git checkout -f . && \
            npm run build